server:
  port: 80
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: USER-CONSUMER-SERVICE #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://USER-CONSUMER-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/**   #断言,路径相匹配的进行路由

        - id: ADMIN-CONSUMER-SERVICE
          uri: lb://ADMIN-CONSUMER-SERVICE
          predicates:
            - Path=/consumer/admin/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

