server:
  port: 82
  max-http-header-size: 1024000
  tomcat:
    max-http-form-post-size: 100MB
spring:
  redis:
    host: 192.168.253.138
  main:
    allow-bean-definition-overriding: true
  feign:
    hystrix:
      enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

  application:
    name: user-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.16.3.10:3306/db_zf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yyf
    password: 123456



# 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）
ribbon:
  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000

eureka:
  client:
    register-with-eureka: true

    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版

    # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: user82
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



