server:
  port: 82

spring:
  redis:
    host: 192.168.253.138
  main:
    allow-bean-definition-overriding: true
  feign:
    hystrix:
      enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

  application:
    name: user-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3366/db_zf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


eureka:
  client:
    register-with-eureka: true

    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版

    # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: user82
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



