server:
  port: 7001

<<<<<<< HEAD
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址


=======

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心,职责是维护实例,并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://yyf.com:7001/eureka #,http://eureka7001.com:7001/eureka #集群指向其他eureka
      defaultZone: http://eureka7001.com:7001/eureka/    #单机就是自己
  server:
    enable-self-preservation: false   #关闭自我保护模式
    eviction-interval-timer-in-ms: 2000    #间隔时间2秒
>>>>>>> b1e461bde3d4952186c45c14330f3c1c875e8812
