server:
  port: 8011
  max-http-header-size: 1024000
  tomcat:
    max-http-form-post-size: 100MB
spring:
  redis:
    host: 192.168.253.138
  application:
    name: earlystage-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.16.3.10:3306/db_zf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yyf
    password: 123456
  rabbitmq:
    host: 192.168.253.138
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual



eureka:
  client:
    register-with-eureka: true

    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #单机版

    # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: earlystage8011
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

